groups/urls.py
from django.urls import path
from . import views

app_name = 'groups'

urlpatterns = [
    path("", views.GroupListView.as_view(), name="all"),
    path("new/", views.GroupCreateView.as_view(), name="create"),
    path("posts/in/<slug:slug>", views.GroupDetailView.as_view(), name="single"),
    path('join/<slug:slug>', views.joinGroup.as_view(), name='join'),
    path('leave/<slug:slug>', views.leaveGroup.as_view(), name='leave'),
]

posts/urls.py
from django.urls import path
from django.conf.urls import url
from . import views

app_name = 'posts'

urlpatterns = [
    path("", views.PostListView.as_view(), name="all"),
    path("new/", views.PostCreateView.as_view(), name="create"),
    url(r"by/(?P<username>[-\w]+)/$",
        views.UserPostsListView.as_view(), name="for_user"),
    url(r"by/(?P<username>[-\w]+)/(?P<pk>\d+)/$",
        views.PostDetailView.as_view(), name="single"),
    path("delete/<int:id>/", views.PostDeleteView.as_view(), name='delete'),
]

socialcloneproject/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.HomePage.as_view(), name='homepage'),
    path('accounts/', include('accounts.urls'), name='accounts'),
    path('accounts/', include('django.contrib.auth.urls')),
    path('thanks/', views.thanksView.as_view(), name='thanks'),
    path('test/', views.testView.as_view(), name='test'),
    path('groups/', include('groups.urls'), name='groups'),
    path('posts/', include('posts.urls'), name='posts'),
]

groups/models.py
import misaka as m
from django.db import models
from django.utils.text import slugify
from django.contrib.auth import get_user_model
from django.urls import reverse
from django import template


User = get_user_model()

register = template.Library()


class Group(models.Model):
    name = models.CharField(max_length=255, unique=True)
    slug = models.SlugField(allow_unicode=True, unique=True)
    descreption = models.TextField(blank=True, default='')
    descreption_html = models.TextField(editable=False, default='', blank=True)
    members = models.ManyToManyField("accounts.User", through='GroupMember')

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        self.descreption_html = m.html(self.descreption)
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('groups:single', kwargs={'slug': self.slug})

    class Meta:
        ordering = ['name']


class GroupMember(models.Model):
    group = models.ForeignKey(
        "groups.Group", related_name="membership", on_delete=models.CASCADE)
    user = models.ForeignKey(
        "accounts.User", related_name="user_groups", on_delete=models.CASCADE)

    def __str__(self):
        return self.user.username

    class Meta:
        unique_together = ('group', 'user')

groups/views.py
from django.shortcuts import render
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.urls import reverse
from django.views.generic import CreateView, ListView, DetailView, RedirectView
from groups.models import Group, GroupMember
from django.contrib import messages
from django.shortcuts import get_object_or_404
from django.db import IntegrityError


class GroupCreateView(CreateView):
    model = Group
    fields = ('name', 'descreption')
    template_name = "groups/group_form.html"


class GroupListView(ListView):
    model = Group
    template_name = "groups/group_list.html"


class GroupDetailView(DetailView):
    model = Group
    template_name = "groups/group_detail.html"


class joinGroup(LoginRequiredMixin, RedirectView):
    def get_redirect_url(self, *args, **kwargs):
        return reverse('groups:single', kwargs={'slug': self.kwargs.get('slug')})

    def get(self, request, *args, **kwargs):
        group = get_object_or_404(Group, slug=self.kwargs.get('slug'))

        try:
            GroupMember.objects.create(user=self.request.user, group=group)
        except IntegrityError:
            messages.warning(self.request, 'Warning!, already a memeber!')
        else:
            messages.success(self.request, 'you are a memeber now')
        return super().get(request, *args, **kwargs)


class leaveGroup(LoginRequiredMixin, RedirectView):
    def get_redirect_url(self, *args, **kwargs):
        return reverse('groups:single', kwargs={'slug': self.kwargs.get('slug')})

    def get(self, request, *args, **kwargs):
        try:
            membership = GroupMember.objects.filter(
                user=self.request.user, group__slug=self.kwargs.get('slug')).get()
        except models.GroupMember.DoesNotExist:
            messages.warning(
                self.request, 'Sorry, you are not a member of this group!')
        else:
            membership.delete()
            messages.success(self.request, 'you left the group now')
        return super().get(request, *args, **kwargs)

groups/templates/groups/group_base.html
{% extends 'base.html' %}

{% block content %}

    <div class='row'>

        {% block pregroup %} {% endblock pregroup %}
        {% block group_content %} {% endblock group_content %}
        {% block postgroup %} {% endblock postgroup %}
        
    </div>

{% endblock content %}

groups/templates/groups/group_detail.html
{% extends 'groups/group_base.html' %}

{% block pregroup %}
    <h1> {{group.name}} </h1>
    <h2> Members : {{group.memeber.count}} </h2>

    <div class='content'>
        {% if user in group.members.all %}
            <a href={% url 'groups:leave' slug=group.slug %} 
            class='btn btn-lg btn-warning'>Leave</a>

        {% else %}
            <a href={% url 'groups:join' slug=group.slug %} 
            class='btn btn-lg btn-warning'>Join</a>

        {% endif %}
    </div>
{% endblock pregroup %}

{% block group_content %}
    <div> 
        {% if group.posts.count == 0%}
            No Posts in this group yet !
        {% else %}
            {% for post in group.posts.all %}
                {% include 'posts/_post.html' %}
            {% endfor %}
        {% endif %}
    </div>
{% endblock group_content %}

groups/templates/groups/group_form.html
{% extends 'groups/group_base.html' %}
{% load bootstrap3 %}

{% block group_content %}
    <div class="container">
        <h1> create new group</h1>

        <form action="{% url 'groups:create' %}" method="post" class="form">
            {% csrf_token %}
            {% bootstrap_form form %}
            {% buttons %}
                <button type="submit" class="btn btn-warning">create group</button>
            {% endbuttons %}
        </form>
    </div>
{% endblock group_content %}

groups/templates/groups/group_list.html
{% extends 'groups/group_base.html' %}

{% block pregroup %}
<div class='col-md-4'>
    <div class='content'>
        {% if user.is_authenticated %}
        Welcome Back
        <a href={% url 'posts:for_user' uesrname=user.username %}>{{user.username}} </a>
        {% endif %}

        Groups
        welcome to the group page!

    </div>

    {% if user.is_authenticated %}
        <a href={% url 'groups:create' %} 
        class='btn btn-lg btn-danger'> create new group</a>
    {% endif %}
</div>
{% endblock pregroup %}

{% block group_content %}
<div class="list-group">
    {% for group in object.list %}
        <a href="{% url 'groups:single' slug=group.slug%}" class="list-group-item list-group-item-action">
            <div class="d-flex w-100 justify-content-between">
              <h5 class="mb-1"> {{group.name}} </h5>
              <small class="text-muted"> {{group.post.count}} Post {{group.post.count|pluralize}} </small>
            </div>
            <p class="mb-1">{{group.descreption_html|safe}} </p>
            <small class="text-muted"> {{group.members.count}} Member{{group.members.count|pluralize}} </small>
        </a>
    {% endfor %}
</div>
{% endblock group_content %}