groups/urls.py
from django.urls import path
from . import views

app_name = 'groups'

urlpatterns = [
    path("", views.GroupListView.as_view(), name="all"),
    path("new/", views.GroupCreateView.as_view(), name="create"),
    path("posts/in/<slug:slug>", views.GroupDetailView.as_view(), name="single"),
    path('join/<slug:slug>', views.joinGroup.as_view(), name='join'),
    path('leave/<slug:slug>', views.leaveGroup.as_view(), name='leave'),
]

posts/urls.py
from django.urls import path
from django.conf.urls import url
from . import views

app_name = 'posts'

urlpatterns = [
    path("", views.PostListView.as_view(), name="all"),
    path("new/", views.PostCreateView.as_view(), name="create"),
    url(r"by/(?P<username>[-\w]+)/$",
        views.UserPostsListView.as_view(), name="for_user"),
    url(r"by/(?P<username>[-\w]+)/(?P<pk>\d+)/$",
        views.PostDetailView.as_view(), name="single"),
    path("delete/<int:id>/", views.PostDeleteView.as_view(), name='delete'),
]

socialcloneproject/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.HomePage.as_view(), name='homepage'),
    path('accounts/', include('accounts.urls'), name='accounts'),
    path('accounts/', include('django.contrib.auth.urls')),
    path('thanks/', views.thanksView.as_view(), name='thanks'),
    path('test/', views.testView.as_view(), name='test'),
    path('groups/', include('groups.urls'), name='groups'),
    path('posts/', include('posts.urls'), name='posts'),
]

templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    {% load static %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="{% static 'css/master.css' %}">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
        integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <title> {% block title %} {% endblock title %}</title>
</head>

<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo01" aria-controls="navbarTogglerDemo01" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarTogglerDemo01">
        <a class="navbar-brand" href="{% url 'homepage' %}">Social</a>
        <ul class="navbar-nav navbar-right">

            {% if user.is_authenticated %}
                
                <li class="nav-item ">
                  <a class="nav-link" href="{% url 'posts:all' %}">Posts </a>
                </li>
                <li class="nav-item ">
                  <a class="nav-link" href="{% url 'groups:all' %}">Groups </a>
                </li>
                <li class="nav-item ">
                  <a class="nav-link" href="{% url 'groups:create' %}">Create Group </a>
                </li>
                <li class="nav-item ">
                  <a class="nav-link" href="{% url 'logout' %}">Logout </a>
                </li>
            {% else %}
                 <li class="nav-item ">
                  <a class="nav-link" href="{% url 'groups:all' %}">Groups </a>
                </li>
                <li class="nav-item ">
                  <a class="nav-link" href="{% url 'login' %}">login </a>
                </li>
                <li class="nav-item ">
                  <a class="nav-link" href="{% url 'signup' %}">Sign Up </a>
                </li>
            
            {% endif %}
          
         
          
          
        </ul>
        
      </div>
    </nav>
    <div class="container">
        {% block content %}
        {% endblock content %}
    </div>
    

    <footer class="container mt-auto">
        <p>Copyright © {% now "Y" %} <a href="https://www.linkedin.com/in/hossamhassan74/">Hossam Hassan</a> </p>
    </footer>

    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js"
        integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
        integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
        crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
        integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6"
        crossorigin="anonymous"></script>
</body>

</html>

templates/index.html
{% extends 'base.html' %}
{% block title %}  Homepage{% endblock title %}

{% block content %}
    
 hello there
    
{% endblock content %}

templates/test.html
{% extends 'base.html' %}
{% block title %}  Loged in {% endblock title %}

{% block content %}
    
    WElcome, happy to see you again!     
{% endblock content %}

templates/thanks.html
{% extends 'base.html' %}
{% block title %} LOGGED OUT  {% endblock title %}

{% block content %}
    GoodBye, hope to see you soon!    
{% endblock content %}