groups/urls.py
from django.urls import path
from . import views

app_name = 'groups'

urlpatterns = [
    path("", views.GroupListView.as_view(), name="all"),
    path("new/", views.GroupCreateView.as_view(), name="create"),
    path("posts/in/<slug:slug>", views.GroupDetailView.as_view(), name="single"),
    path('join/<slug:slug>', views.joinGroup.as_view(), name='join'),
    path('leave/<slug:slug>', views.leaveGroup.as_view(), name='leave'),
]

posts/urls.py
from django.urls import path
from django.conf.urls import url
from . import views

app_name = 'posts'

urlpatterns = [
    path("", views.PostListView.as_view(), name="all"),
    path("new/", views.PostCreateView.as_view(), name="create"),
    url(r"by/(?P<username>[-\w]+)/$",
        views.UserPostsListView.as_view(), name="for_user"),
    url(r"by/(?P<username>[-\w]+)/(?P<pk>\d+)/$",
        views.PostDetailView.as_view(), name="single"),
    path("delete/<int:id>/", views.PostDeleteView.as_view(), name='delete'),
]

socialcloneproject/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.HomePage.as_view(), name='homepage'),
    path('accounts/', include('accounts.urls'), name='accounts'),
    path('accounts/', include('django.contrib.auth.urls')),
    path('thanks/', views.thanksView.as_view(), name='thanks'),
    path('test/', views.testView.as_view(), name='test'),
    path('groups/', include('groups.urls'), name='groups'),
    path('posts/', include('posts.urls'), name='posts'),
]

posts/models.py
from django.db import models
from django.urls import reverse
from django.conf import settings
from groups.models import Group
from django.contrib.auth import get_user_model
import misaka

User = get_user_model()


class Post(models.Model):
    user = models.ForeignKey(
        "accounts.User", related_name='posts', on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now=True, auto_now_add=False)
    message = models.TextField()
    message_html = models.TextField(editable=False)
    group = models.ForeignKey(
        "groups.Group", related_name='posts', null=True, blank=True, on_delete=models.CASCADE)

    def __str__(self):
        return self.message

    def save(self, *args, **kwargs):
        self.message_html = misaka.html(self.message)
        super().save(*args, **kwargs)

    class Meta:
        ordering = ['-created_at']
        unique_together = ['user', 'message']

posts/views.py
from django.shortcuts import render
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth import get_user_model
from django.urls import reverse_lazy
from django.http import Http404
from django.views.generic import ListView, DetailView, CreateView, DeleteView
from braces.views import SelectRelatedMixin
from posts import models, forms
from django.contrib import messages


User = get_user_model()


class PostListView(SelectRelatedMixin, ListView):
    model = models.Post
    select_related = ('user', 'group')


class UserPostsListView(ListView):
    model = models.Post
    template_name = "posts/user_post_list.html"

    def get_queryset(self):
        try:
            self.post_user = User.objects.prefetch_related('posts').get(
                username__iexact=self.kwargs.get('username'))
        except User.DoesNotExist:
            raise Http404
        else:
            return self.post_user.posts.all()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["post_user"] = self.post_user
        return context


class PostDetailView(SelectRelatedMixin, DetailView):
    model = models.Post
    select_related = ('user', 'group')

    def get_queryset(self):
        queryset = super().get_queryset()
        return queryset.filter(user__username__iexact=self.kwargs.get('username'))


class PostCreateView(LoginRequiredMixin, SelectRelatedMixin, CreateView):
    model = models.Post
    fields = ('message', 'group')

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.user = self.request.user
        self.object.save()
        return super().form_valid(form)


class PostDeleteView(LoginRequiredMixin, SelectRelatedMixin, DeleteView):
    model = models.Post
    select_related = ('user', 'group')
    success_url = reverse_lazy('posts:all')

    def get_queryset(self):
        return super().get_queryset().filer(user_id=self.request.user.id)

    def delete(self, *args, **kwargs):
        messages.success(self.request, 'Post Deleted')
        return super().delete(*args, **kwargs)

posts/templates/posts/_post.html
<h3>{{post.message_html|safe}}</h3>
<strong>{{post.user.username}} </strong>
<h5>
    <a href="{% url 'posts:for_user' username=post.user.username %}"></a>
    <a href="{% url 'posts:single' username=post.user.username pk=post.pk %}"></a>
</h5>

<div>
    {% if user.is_authenticated and post.user == user %}
        <a href="{% url 'posts:delete' pk=post.pk %}">Delete</a>

    {% endif %}
</div>

posts/templates/posts/post_base.html
{% extends 'base.html' %}

{% block content %}
    
    <div class="post_page">
        <div class="container">
            <div class="row">
                {% block prepost %} {% endblock prepost %}
                {% block post_content %} {% endblock post_content %}
                {% block post_post %} {% endblock post_post %}
            </div>
        </div>
    </div>
       

{% endblock content %}

posts/templates/posts/post_confirm_delete.html
{% extends 'posts/post_base.html' %}

{% block post_content %}
<h3>Are You sure you want to delete the post</h3>

{% include 'posts/_post.html' {% with post as object %} {% endwith %}%}

<form method="post">
    {% csrf_token %}
    <input type="submit" value="Confirm Delete" class="btn-danger btn btn-lg">
    <a href="{% url 'posts:single' username=user.username pk=object.pk%}">Cancel</a>
</form>
{% endblock post_content %}

posts/templates/posts/post_detail.html
{% extends 'posts/post_base.html' %}

{% block prepost %}
    <h1> {{post.user.username}} </h1>
{% endblock prepost %}

{% block post_content %}
    {% for post in post_list %}
        {% include 'posts/_post.html' %}
    {% endfor %}
{% endblock post_content %}

posts/templates/posts/post_form.html
{% extends 'posts/post_base.html' %}
{% load bootstrap3 %}

{% block post_content %}
    
    <h1> Create New Post</h1>
    <form id='postForm' action="{% url 'posts:create' %}" method="post" class="form">
        {% csrf_token %}
        {% bootstrap_form form %}
        {% buttons %}
            <button type="submit" value='Post' class="btn btn-warning">Publish!</button>
        {% endbuttons %}
    </form>

{% endblock post_content %}

posts/templates/posts/post_list.html
{% extends 'posts/post_base.html' %}

{% block prepost %}
<div class='col-md-4'>
  {% if user.is_authenticated %}
    <h1>your groups</h1>
    <br>
    <ul>
      {% for member_group in get_user_groups %}
        <li><a href="{% url 'groups:single' slug=member_group.group.slug %}"></a></li>
      {% endfor %}
    </ul>  

  {% endif %}

  <h1>all groups</h1>
  <br>
  <ul>
    {% for other_group in get_other_groups %}
      <li><a href="{% url 'groups:single' slug=other_group.group.slug %}"></a></li>
    {% endfor %}
  </ul>  
</div>
{% endblock prepost %}

{% block post_content %}

  {% for post in post_list %}
    {% include 'posts/_post.html' %}
  {% endfor %}
{% endblock post_content %}